version: "2.1"

services:
  app:
    build: ./app
    restart: always
    volumes:
      - ./app:/app
      - ./db:/db
      - ${MODFLOW_DATA}:/modflow
    ports:
      - "5000:5000"
    networks:
      - web
      - default

  worker:
    build: ./worker
    restart: always
    volumes:
      - ./worker:/app
      - ./db:/db
      - ${MODFLOW_DATA}:/modflow
    command: [ "python", "-u", "worker.py" ]
