version: "3.7"

services:
  app:
    build: ./app
    restart: always
    volumes:
      - ./app:/app
      - ./db:/db
      - ${MODFLOW_DATA}:/modflow
    ports:
      - "5000:5000"

  worker:
    build: ./worker
    restart: always
    volumes:
      - ./worker:/app
      - ./db:/db
      - ${MODFLOW_DATA}:/modflow
    command: [ "python", "-u", "worker.py" ]
