version: "2.1"

services:
  app:
    build: ./app
    restart: always
    expose:
      - 5000
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.wiki.frontend.rule=Host: ${HOST_URL}"
      - "traefik.wiki.port=5000"
      - "traefik.wiki.protocol=http"
    networks:
      - web
    volumes:
      - ./app:/app
      - ./db:/db
      - ${MODFLOW_DATA}:/modflow

  worker:
    build: ./worker
    restart: always
    volumes:
      - ./worker:/app
      - ./db:/db
      - ${MODFLOW_DATA}:/modflow
    command: ["python", "-u", "worker.py"]

  traefik:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme.json:/acme.json
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/logs:/logs

networks:
  web:
    external: true