version: "2"

services:
  app:
    image: inowas/modflow-service:dev
    restart: always
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.wiki.frontend.rule=Host: ${HOST_URL}"
      - "traefik.wiki.port=5000"
      - "traefik.wiki.protocol=http"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    networks:
      - web
      - default
    volumes:
      - ./db:/db
      - ${MODFLOW_DATA}:/modflow
    command: [ "python", "-u", "app.py" ]

  worker:
    image: inowas/modflow-service:dev
    restart: always
    volumes:
      - ./db:/db
      - ${MODFLOW_DATA}:/modflow
    command: [ "python", "-u", "worker.py" ]

networks:
  web:
    external: true